version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    networks:
      - netwerk2
  backend:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - netwerk2
    environment:
      - host=db
      - db_username=username
      - db_password=UnhAckablePassword
      - params=?authSource=admin
      - EXPRESS_PORT=5000
  db-exporter:
    image: bitnami/mongodb-exporter:0.11
    environment:
      - MONGODB_URI=mongodb://db:27017
    restart: always
    ports: 
      - 9216:9216
    networks:
      - netwerk2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - db
      - backend
      - frontend
    networks:
      - netwerk2

  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - netwerk2
  db:
    image: mongo
    networks:
      - netwerk2
    environment:
      - MONGO_INITDB_DATABASE=Connections
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=UnhAckablePassword
    volumes:
      - ./mongo-volume:/data/db
volumes:
  prometheus-data:

networks:
  netwerk2:
